import {Injectable} from '@angular/core';

@Injectable()
export class OrderService {

  orderData = [
    {
      orderId: 1000,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
    {
      orderId: 1001,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1002,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1003,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1004,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1005,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1006,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1007,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1008,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1009,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1010,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1011,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    },
	{
      orderId: 1012,
      shipDate: 'Jan-20-2017',
      deliveryDate: 'Feb-1-2017',
      transitDays: '12',
      weight: '2.5kg',
      volume: '28',
	  fromLocation: 'New York',
	  fromAddress: 'Baker Street',
	  fromContact: '1-450-324-1234',
	  toLocation: 'London',
	  toAddress: 'Wood Ave',
	  toContact: 'Mary',
	  cargoValue: '304',
	  orderStatus: 'Shipped',
	  shipper: 'UPS',
	  consignee: 'DHL',
	  creationDate: 'Jan-5-2017',
	  creationBy: 'Jesse',
	  lastUpdateDate: 'Jan-10-2017',
	  lastUpdateBy: 'Jesse'
    }
  ];

  metricsTableData = [
    {
      image: 'app/browsers/chrome.svg',
      browser: 'Google Chrome',
      visits: '10,392',
      isVisitsUp: true,
      purchases: '4,214',
      isPurchasesUp: true,
      percent: '45%',
      isPercentUp: true
    },
    {
      image: 'app/browsers/firefox.svg',
      browser: 'Mozilla Firefox',
      visits: '7,873',
      isVisitsUp: true,
      purchases: '3,031',
      isPurchasesUp: false,
      percent: '28%',
      isPercentUp: true
    },
    {
      image: 'app/browsers/ie.svg',
      browser: 'Internet Explorer',
      visits: '5,890',
      isVisitsUp: false,
      purchases: '2,102',
      isPurchasesUp: false,
      percent: '17%',
      isPercentUp: false
    },
    {
      image: 'app/browsers/safari.svg',
      browser: 'Safari',
      visits: '4,001',
      isVisitsUp: false,
      purchases: '1,001',
      isPurchasesUp: false,
      percent: '14%',
      isPercentUp: true
    },
    {
      image: 'app/browsers/opera.svg',
      browser: 'Opera',
      visits: '1,833',
      isVisitsUp: true,
      purchases: '83',
      isPurchasesUp: true,
      percent: '5%',
      isPercentUp: false
    }
  ];

  getData(): Promise<any> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(this.orderData);
      }, 2000);
    });
  }
}
